[build]
  command = "pip install -r requirements.txt && gunicorn -b 0.0.0.0:8000 functions.app:server"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "functions"